name: ci
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        npm-test:
        - i18n_extract
        - lint
        - test
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: '.nvmrc'
    - run: make requirements
    - run: make test NPM_TESTS=build
    - run: make test NPM_TESTS=${{ matrix.npm-test }}
    - name: Coverage
      if: ${{ matrix.npm-test == 'test' }}
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
